<?php

/**
 * @file
 * Contains hello_world.module..
 */

use Drupal\Core\Entity\EntityInterface;
use Drupal\Core\Entity\Display\EntityViewDisplayInterface;

/**
 * Implements hook_entity_view().
 */
function hello_world_entity_view(array &$build, EntityInterface $entity, EntityViewDisplayInterface $display) {
  if ($entity->getEntityTypeId() == 'node' &&
      $entity->bundle() == 'hello_world_article') {

    // Alter build array to include message.
    $build['hello_world'] = [
      '#markup' => '<em>' . t('Content starts here!') . '</em>',
      '#weight' => $build['body']['#weight'] - 1, // Just above the body.
    ];
  }
}
