<?php

namespace Drupal\hello_world\Plugin\Block;

use Drupal\Core\Block\BlockBase;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Drupal\Core\Entity\Query\Sql\QueryFactory;
use Drupal\Core\Form\FormStateInterface;
use Drupal\node\Entity\Node;

/**
 * Provides a 'HelloBlock' block.
 *
 * @Block(
 *  id = "hello_block",
 *  admin_label = @Translation("Hello block"),
 * )
 */
class HelloBlock extends BlockBase {

  /**
   * The entity query manager.
   *
   * @var \Drupal\Core\Entity\Query\Sql\QueryFactory
   */
  private $entityQueryManager;

  /**
   * {@inheritdoc}
   */
  public function __construct(array $configuration, $plugin_id, $plugin_definition) { //}, QueryFactory $entity_query) {
    parent::__construct($configuration, $plugin_id, $plugin_definition);
  }

//  /**
//   * {@inheritdoc}
//   */
//  public static function create(ContainerInterface $container, array $configuration, $plugin_id, $plugin_definition) {
//    return new static(
//      $configuration,
//      $plugin_id,
//      $plugin_definition,
//      $container->get('entity.query')
//    );
//  }

  /**
   * {@inheritdoc}
   */
  public function build() {
    $config = $this->getConfiguration();

    $build = [
      '#attached' => [
        'library' => [
          'hello_world/hello_world.hello_block',
        ],
      ],
      '#cache' => [
        'max-age' => $config['hello_block_cache_max_age'],
      ],
    ];

    // Query for published Hello World Articles with the given tags.
    $entity_query = \Drupal::entityQuery('node')
      ->condition('status', '1')
      ->condition('type', 'hello_world_article')
      ->condition('field_sections.entity.name', ['About Us', 'Misc', 'News'], 'IN');

    $result = $entity_query->execute();

    if (empty($result)) {
      // Display an empty message if there are no results.
      $build['hello_block']['#markup'] = $config['empty_text'];
    }
    else {
      // Use Core's links template, but allow easy override.
      $build['hello_block'] = [
        '#theme' => 'links__hello',
        '#attributes' => [
          'class' => [],
        ],
      ];

      // Load all the nodes at once.
      $nodes = Node::loadMultiple($result);

      foreach ($nodes as $node) {
        // Add to links array.
        $build['hello_block']['#links'][] = [
          'title' => $node->label(),
          'url' => $node->urlInfo(),
        ];
      }
    }

    return $build;
  }

  public function defaultConfiguration() {
    return [
      'hello_block_cache_max_age' => 60,
      'empty_text' => t('There are no Hello articles to display.'),
    ];
  }

  public function blockForm($form, FormStateInterface $form_state) {
    $config = $this->getConfiguration();

    $form['empty_text'] = [
      '#type' => 'textfield',
      '#title' => t('No-results text'),
      '#description' => t('The text to display when no Hello World Articles are found.'),
      '#default_value' => $config['empty_text'],
      '#size' => 60,
      '#maxlength' => 255,
      '#required' => TRUE,
    ];

    $form['cache_max_age'] = [
      '#type' => 'select',
      '#title' => t('Cache results'),
      '#default_value' => $config['hello_block_cache_max_age'],
      '#description' => t('The period to refresh the links displayed in the block.'),
      '#options' => [
        '0' => 'Never, don\'t cache',
        '60' => '1 minute',
        '300' => '5 minutes',
        '3600' => '1 hour',
        \Drupal\Core\Cache\Cache::PERMANENT => 'Forever',
      ],
    ];

    return $form;
  }

  public function blockSubmit($form, FormStateInterface $form_state) {
    parent::blockSubmit($form, $form_state); // TODO: Change the autogenerated stub
  }
}
